import streamlit as st  
from PIL import Image  
def teams_map(option):
  if option=="Boston Celtics"
  if option=="Brooklyn Nets"
  if option=="New York Knicks"
  if option=="Philadelphia 76ers"
  if option=="Toronto Raptors"
  if option=="Chicago Bulls"
  if option=="Cleveland Cavaliers"
  if option=="Detroit Pistons"
  if option=="Indiana Pacers"
  if option=="Milwaukee Bucks"
  if option=="Atlanta Hawks"
  if option=="Charlotte Hornets"
  if option=="Miami Heat"
  if option=="Orlando Magic"
  if option=="Washington Wizards"
  if option=="Denver Nuggets"
  if option=="Minnesota Timberwolves"
  if option=="Oklahoma City Thunder"
  if option=="Portland Trail Blazers"
  if option=="Utah Jazz"
  if option=="Golden State Warriors"
  if option=="Los Angeles Clippers"
  if option=="Los Angeles Lakers"
  if option=="Phoenix Suns"
  if option=="Sacramento Kings"
  if option=="Dallas Mavericks"
  if option=="Houston Rockets"
  if option=="Memphis Grizzlies"
  if option=="New Orleans Pelicans"
  if option=="San Antonio Spurs"
